controller:
  admin.username: admin
  admin.password: Admin@123

  image:
    repository: jenkins/jenkins
    tag: lts-jdk17

  serviceType: LoadBalancer

  JCasC:
    enabled: true
    defaultConfig: false
    configScripts:
      main-config: |
        {{- (.Files.Get "jcasc/jenkins.yaml") | nindent 8 }}

  sidecars:
    configAutoReload:
      enabled: false
    
persistence:
  enabled: true
  storageClass: managed-csi-premium
  size: 20Gi
